from enum import Enum
# Token types for our language
class TokenType(Enum):
    IF = 'IF'
    ELSE = 'ELSE'
    FOR = 'FOR'
    DEF = 'DEF'
    RETURN = 'RETURN'
    STRUCT = 'STRUCT'
    PRINT = 'PRINT'
    TRUE = 'TRUE'
    FALSE = 'FALSE'
    AND = 'AND'
    OR = 'OR'
    NOT = 'NOT'
    EQUAL = 'EQUAL'
    NOT_EQUAL = 'NOT_EQUAL'
    LESS = 'LESS'
    GREATER = 'GREATER'
    LESS_EQUAL = 'LESS_EQUAL'
    GREATER_EQUAL = 'GREATER_EQUAL'
    ASSIGN = 'ASSIGN'  # =
    PLUS = 'PLUS'
    MINUS = 'MINUS'
    MULTIPLY = 'MULTIPLY'
    DIVIDE = 'DIVIDE'
    EXPONENTIATION = 'EXPONENTIATION'
    MODULUS = 'MODULUS'
    NUMBER = 'NUMBER'
    STRING = 'STRING'
    ID = 'ID'
    LPAREN = 'LPAREN'
    RPAREN = 'RPAREN'
    LBRACE = 'LBRACE'
    RBRACE = 'RBRACE'
    DOT = 'DOT'
    COMMA = 'COMMA'
    SEMICOLON = 'SEMICOLON'
    EOF = 'EOF'